// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVGRo6-Vbi05TlG0tw-FzotkEADjXqo1U',
    appId: '1:676428324320:web:f18aa45f645a0cc4ea9f85',
    messagingSenderId: '676428324320',
    projectId: 'stayfit-90e1a',
    authDomain: 'stayfit-90e1a.firebaseapp.com',
    storageBucket: 'stayfit-90e1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuL7yFZEUrwfNs_yeIUikwB7ykAXTST4s',
    appId: '1:676428324320:android:1d67e18433c33b4fea9f85',
    messagingSenderId: '676428324320',
    projectId: 'stayfit-90e1a',
    storageBucket: 'stayfit-90e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz_OKt5q2C0KNNxKl0dG4E3rTyoqquWzo',
    appId: '1:676428324320:ios:caff0639862a0d5dea9f85',
    messagingSenderId: '676428324320',
    projectId: 'stayfit-90e1a',
    storageBucket: 'stayfit-90e1a.appspot.com',
    iosBundleId: 'com.example.stayFit',
  );
}
